---
apiVersion: v1
kind: Service
metadata: 
  name: ambari
  namespace: bigdata
spec:
  ports:
    - name: tcp-8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: ambari
  namespace: bigdata
subsets:
- addresses:
  - ip: 10.78.204.14
  ports:
  - name: ambari
    port: 8080
    protocol: TCP
  
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ambari
  namespace: bigdata
spec:
  http:
  - backends:
    - serviceName: ambari
      servicePort: 80
    match:
      hosts:
      - ambari-ui.sea.example.com
      paths:
      - /*
    name: ambari
